ZETES_FEET_PATH = ../target
ZETES_HANDS_PATH = ../target

APPLICATION_NAME = BellardPI
BINARY_NAME = bellardpi

all: app

include $(ZETES_HANDS_PATH)/User.mk
include ../common-scripts/ideconf/ideconf.mk
