ZETES_FEET_PATH = ../target
ZETES_HANDS_PATH = ../target

APPLICATION_NAME = BellardPI
BINARY_NAME = bellardpi

TARGET = target

all: app

include $(ZETES_HANDS_PATH)/ZetesHands.mk
include ../common-scripts/ideconf/ideconf.mk
