ZETES_PATH = ../zetes

APPLICATION_NAME = Flyer
BINARY_NAME = flyer
ENTRY_CLASS = flyer/FlyerApplication

include $(ZETES_PATH)/common-scripts/globals.mk
include $(ZETES_WINGS_PATH)/ZetesWings.mk

all: app
